import { PortfolioItem, Service, Testimonial, Inquiry } from "@/types/database";

export const mockSettings: Record<string, string> = {
  hero_title: "Beauty, Elevated",
  hero_subtitle: "Professional makeup artistry for your most important moments",
  hero_image: "",
  about_title: "About Me",
  about_bio: "I am a professional makeup artist with over 8 years of experience specializing in bridal, editorial, and special occasion makeup. My mission is to enhance your natural beauty and make you feel confident and radiant for every occasion.\n\nFrom the soft glow of a bridal look to the bold creativity of editorial shoots, I bring passion, precision, and a deep understanding of beauty to every client I work with.",
  about_image: "",
  contact_email: "hello@example.com",
  contact_phone: "(310) 555-0123",
  contact_location: "Los Angeles, CA",
  social_instagram: "https://instagram.com",
  social_facebook: "https://facebook.com",
  social_tiktok: "https://tiktok.com",
  footer_text: "Professional makeup artistry for weddings, editorials, and special occasions.",
};

export const mockPortfolioItems: PortfolioItem[] = [
  {
    id: "p1",
    title: "Romantic Garden Wedding",
    slug: "romantic-garden-wedding",
    description: "Soft glam bridal look with dewy skin, soft pink lips, and fluttery lashes. Perfect for this outdoor spring wedding in Malibu. The bride wanted a natural yet elevated look that would photograph beautifully in golden hour light.",
    category: "bridal",
    cover_image_url: null,
    images: [],
    is_featured: true,
    display_order: 1,
    is_published: true,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "p2",
    title: "Editorial Beauty for Vogue",
    slug: "editorial-beauty-vogue",
    description: "Bold editorial look featuring graphic liner and a statement red lip for a high-fashion magazine spread. This shoot required precision and creativity to bring the creative director's vision to life.",
    category: "editorial",
    cover_image_url: null,
    images: [],
    is_featured: true,
    display_order: 2,
    is_published: true,
    created_at: "2025-02-10T10:00:00Z",
    updated_at: "2025-02-10T10:00:00Z",
  },
  {
    id: "p3",
    title: "Sunset Gala Glam",
    slug: "sunset-gala-glam",
    description: "Warm-toned smokey eye with bronzed skin and nude lip for a black-tie charity gala. The look was designed to complement the client's burgundy gown.",
    category: "occasions",
    cover_image_url: null,
    images: [],
    is_featured: true,
    display_order: 3,
    is_published: true,
    created_at: "2025-03-05T10:00:00Z",
    updated_at: "2025-03-05T10:00:00Z",
  },
  {
    id: "p4",
    title: "Spring Bridal Collection",
    slug: "spring-bridal-collection",
    description: "A collection of fresh, spring-inspired bridal looks featuring soft pastels and luminous skin.",
    category: "bridal",
    cover_image_url: null,
    images: [],
    is_featured: false,
    display_order: 4,
    is_published: true,
    created_at: "2025-04-01T10:00:00Z",
    updated_at: "2025-04-01T10:00:00Z",
  },
  {
    id: "p5",
    title: "Avant-Garde Editorial",
    slug: "avant-garde-editorial",
    description: "Pushing boundaries with artistic makeup for an avant-garde fashion editorial.",
    category: "editorial",
    cover_image_url: null,
    images: [],
    is_featured: false,
    display_order: 5,
    is_published: true,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "p6",
    title: "Prom Night Glam",
    slug: "prom-night-glam",
    description: "Age-appropriate glam looks for prom season. Sparkle, shimmer, and confidence.",
    category: "occasions",
    cover_image_url: null,
    images: [],
    is_featured: false,
    display_order: 6,
    is_published: false,
    created_at: "2025-05-01T10:00:00Z",
    updated_at: "2025-05-01T10:00:00Z",
  },
];

export const mockServices: Service[] = [
  {
    id: "s1",
    name: "Bridal Makeup",
    description: "Full bridal glam including trial session, day-of application, and touch-up kit. Includes lashes and setting spray for all-day wear.",
    price: 350,
    price_note: "starting at",
    duration: "2-3 hours",
    category: "bridal",
    display_order: 1,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
  },
  {
    id: "s2",
    name: "Bridal Party",
    description: "Coordinated makeup for bridesmaids and mothers. Consistent, beautiful looks that complement the bride.",
    price: 120,
    price_note: "per person",
    duration: "45 min each",
    category: "bridal",
    display_order: 2,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
  },
  {
    id: "s3",
    name: "Editorial / Photoshoot",
    description: "Creative or clean beauty looks for magazines, campaigns, lookbooks, and content creation.",
    price: 250,
    price_note: "per session",
    duration: "1-2 hours",
    category: "editorial",
    display_order: 3,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
  },
  {
    id: "s4",
    name: "Special Occasion",
    description: "Prom, gala, date night, or any event where you want to look and feel amazing.",
    price: 150,
    price_note: null,
    duration: "1 hour",
    category: "occasions",
    display_order: 4,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
  },
  {
    id: "s5",
    name: "Makeup Lesson",
    description: "One-on-one session where I teach you techniques customized to your face shape, skin type, and style goals.",
    price: 200,
    price_note: null,
    duration: "1.5 hours",
    category: "lessons",
    display_order: 5,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    client_name: "Sarah M.",
    content: "She made me feel like the most beautiful version of myself on my wedding day. My makeup lasted from morning until 2am and still looked flawless in every photo.",
    image_url: null,
    service_type: "Bridal",
    rating: 5,
    is_featured: true,
    is_published: true,
    created_at: "2025-01-20T10:00:00Z",
    updated_at: "2025-01-20T10:00:00Z",
  },
  {
    id: "t2",
    client_name: "Jessica L.",
    content: "I booked her for a photoshoot and the results were incredible. She understood the creative direction immediately and brought my vision to life.",
    image_url: null,
    service_type: "Editorial",
    rating: 5,
    is_featured: true,
    is_published: true,
    created_at: "2025-02-15T10:00:00Z",
    updated_at: "2025-02-15T10:00:00Z",
  },
  {
    id: "t3",
    client_name: "Amanda R.",
    content: "The makeup lesson was worth every penny. I finally understand how to do a proper smokey eye and my daily routine has completely leveled up.",
    image_url: null,
    service_type: "Lesson",
    rating: 5,
    is_featured: true,
    is_published: true,
    created_at: "2025-03-10T10:00:00Z",
    updated_at: "2025-03-10T10:00:00Z",
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: "i1",
    name: "Emily Johnson",
    email: "emily@example.com",
    phone: "(555) 123-4567",
    service_interest: "Bridal Makeup",
    preferred_date: "2025-09-15",
    message: "Hi! I'm getting married on September 15th and I'd love to book you for bridal makeup. I'll have 4 bridesmaids as well. Can you send me your availability and pricing?",
    status: "new",
    created_at: "2025-06-01T14:30:00Z",
    updated_at: "2025-06-01T14:30:00Z",
  },
  {
    id: "i2",
    name: "Rachel Kim",
    email: "rachel@example.com",
    phone: null,
    service_interest: "Editorial / Photoshoot",
    preferred_date: "2025-07-20",
    message: "I'm a photographer looking for a makeup artist for an upcoming editorial shoot. The theme is ethereal/fantasy. Would you be interested?",
    status: "read",
    created_at: "2025-05-28T09:15:00Z",
    updated_at: "2025-05-29T10:00:00Z",
  },
  {
    id: "i3",
    name: "Maria Santos",
    email: "maria@example.com",
    phone: "(555) 987-6543",
    service_interest: "Makeup Lesson",
    preferred_date: null,
    message: "I'd love to book a makeup lesson! I struggle with eyeshadow application and want to learn some everyday techniques.",
    status: "replied",
    created_at: "2025-05-20T16:45:00Z",
    updated_at: "2025-05-21T11:00:00Z",
  },
];
